name: Cron Test
on:
  schedule:
    - cron: '22 8 * * *'
    - cron: '0/15 * * * *'
jobs:
  cron-test:
    runs-on: ubuntu-latest
    steps:
      - name: Running
        shell: bash
        run: echo "Hello world!"
